/* ------------------------------------------------------------------ */
/* Sitemap and robots, generated from the docs map.                     */
/*                                                                      */
/*   node scripts/build-sitemap.mjs                                     */
/*                                                                      */
/* The site is a single-page app behind a catch-all rewrite, so every    */
/* route returns the same HTML and a crawler has no links-to-follow      */
/* trail into the deeper pages until it has run the JavaScript. A        */
/* sitemap is the cheap way to say "these thirty-three URLs exist".      */
/*                                                                      */
/* Generated rather than hand-written, from the same table the sidebar,  */
/* ⌘K, qa.mjs and a11y.mjs already read — so a new page cannot be added  */
/* without appearing here.                                              */
/* ------------------------------------------------------------------ */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const PUBLIC = `${ROOT}apps/docs/public`;

const site = await readFile(`${ROOT}apps/docs/src/lib/site.ts`, "utf8");
const ORIGIN = site.match(/url:\s*"([^"]+)"/)?.[1] ?? "https://hashui.vercel.app";

const routesSrc = await readFile(`${ROOT}apps/docs/src/lib/routes.ts`, "utf8");
const routes = ["/", ...[...routesSrc.matchAll(/path:\s*"([^"]+)"/g)].map((m) => m[1])];

/* The landing page first, then the docs in reading order. Priorities are a
   hint, not a ranking — the landing page and the two install routes are the
   ones worth surfacing. */
const priority = (r) =>
  r === "/" ? "1.0" : /\/docs$|installation|registry/.test(r) ? "0.8" : "0.6";

const urls = routes
  .map(
    (r) =>
      `  <url>\n    <loc>${ORIGIN}${r === "/" ? "/" : r}</loc>\n` +
      `    <changefreq>weekly</changefreq>\n    <priority>${priority(r)}</priority>\n  </url>`,
  )
  .join("\n");

await writeFile(
  `${PUBLIC}/sitemap.xml`,
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!-- generated by scripts/build-sitemap.mjs — do not edit by hand -->\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`,
);

await writeFile(
  `${PUBLIC}/robots.txt`,
  `# generated by scripts/build-sitemap.mjs — do not edit by hand\n` +
    `User-agent: *\nAllow: /\n\n` +
    `# the registry is an API rather than a page; nothing to index\n` +
    `Disallow: /r/\n\n` +
    `Sitemap: ${ORIGIN}/sitemap.xml\n`,
);

console.log(`sitemap: ${routes.length} routes → apps/docs/public/sitemap.xml (+ robots.txt)`);
