/* GENERATED by scripts/build-registry.mjs — do not edit by hand. */

export type RegistryItem = {
  name: string;
  title: string;
  description: string;
  type: string;
  target: string;
  dependencies: string[];
  registryDependencies: string[];
};

export const REGISTRY_ITEMS: RegistryItem[] = [
  {
    "name": "tokens",
    "title": "Design tokens",
    "description": "Every design token in one file: surfaces, ink, brand, the button-face palette, both themes and the utility classes. Import it after Tailwind.",
    "type": "registry:theme",
    "target": "styles/hashui.css",
    "dependencies": [],
    "registryDependencies": []
  },
  {
    "name": "cx",
    "title": "cx",
    "description": "The three-line class-name joiner every component uses. No clsx, no tailwind-merge.",
    "type": "registry:lib",
    "target": "lib/hashui/cx.ts",
    "dependencies": [],
    "registryDependencies": [
      "tokens"
    ]
  },
  {
    "name": "icons",
    "title": "Icons",
    "description": "83 hand-drawn SVG icons on a 24px grid with a shared 1.8 stroke. Tree-shakeable, no icon package.",
    "type": "registry:ui",
    "target": "components/hashui/icons.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens"
    ]
  },
  {
    "name": "theme",
    "title": "ThemeProvider",
    "description": "light / dark / system with a persisted choice, plus the live sans-stack switcher behind useTheme().",
    "type": "registry:ui",
    "target": "components/hashui/theme.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens"
    ]
  },
  {
    "name": "button",
    "title": "Button",
    "description": "One anatomy — vertical gradient, 1px ring, hairline highlight — across eight faces. Plus ButtonGroup, IconButton and SplitButton.",
    "type": "registry:ui",
    "target": "components/hashui/button.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "badge",
    "title": "Badge & pill",
    "description": "StatusPill, DotPill, OutlineBadge, GlowPill, GlowDot, AnnouncementPill, CountBadge and Kbd — the whole status vocabulary.",
    "type": "registry:ui",
    "target": "components/hashui/badge.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "avatar",
    "title": "Avatar",
    "description": "Gradient-initial avatars with presence rings, overlapping AvatarGroup and the EntityChip company mark.",
    "type": "registry:ui",
    "target": "components/hashui/avatar.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "card",
    "title": "Card",
    "description": "Card, InsetPanel, StatTile, OverviewTile and MetaRow — the card-in-card layering the system uses instead of shadows.",
    "type": "registry:ui",
    "target": "components/hashui/card.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "controls",
    "title": "Controls",
    "description": "Switch, Checkbox, SegmentedControl and SearchField.",
    "type": "registry:ui",
    "target": "components/hashui/controls.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons"
    ]
  },
  {
    "name": "inputs",
    "title": "Inputs & selection",
    "description": "Slider, RadioGroup, RadioCards, SelectField, Accordion, Stepper, Pagination and Breadcrumbs.",
    "type": "registry:ui",
    "target": "components/hashui/inputs.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons"
    ]
  },
  {
    "name": "tabs",
    "title": "Tabs",
    "description": "PillTabs, NotchTabs, DotTabs, UnderlineTabs and PillNav — five tab treatments on one item model.",
    "type": "registry:ui",
    "target": "components/hashui/tabs.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "progress",
    "title": "Progress & meters",
    "description": "ProgressBar, TickBars, SignalBars, DottedMeter, GoalBar, RainbowMeter, RingProgress, RangeBar, CountdownLCD and LcdTimer.",
    "type": "registry:ui",
    "target": "components/hashui/progress.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "timeline",
    "title": "Timeline",
    "description": "DeliveryTimeline for ordered steps and StageFlow for service pipelines with protocol connectors.",
    "type": "registry:ui",
    "target": "components/hashui/timeline.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "badge",
      "icons"
    ]
  },
  {
    "name": "commit-graph",
    "title": "CommitGraph",
    "description": "A branching git graph with a hover card and diff counts — built for event-sourced history.",
    "type": "registry:ui",
    "target": "components/hashui/commit-graph.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "avatar",
      "icons"
    ]
  },
  {
    "name": "feedback",
    "title": "Feedback",
    "description": "Alert, ToastProvider + useToast, Tooltip, Skeleton and EmptyState.",
    "type": "registry:ui",
    "target": "components/hashui/feedback.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons"
    ]
  },
  {
    "name": "overlay",
    "title": "Overlay",
    "description": "Modal with focus and Esc handling, ModalClose, and the Dropdown menu.",
    "type": "registry:ui",
    "target": "components/hashui/overlay.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons"
    ]
  },
  {
    "name": "motion",
    "title": "Motion",
    "description": "NumberTicker, Typewriter, Marquee, ShimmerButton, BorderBeam, Spotlight, TiltCard, Reveal, Meteors and GradientText — all dependency-free.",
    "type": "registry:ui",
    "target": "components/hashui/motion.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "three-orb",
    "title": "ThreeOrb",
    "description": "A wireframe three.js scene that imports the library only once it scrolls into view.",
    "type": "registry:ui",
    "target": "components/hashui/three-orb.tsx",
    "dependencies": [
      "three"
    ],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "hashui",
    "title": "HashUI — the whole library",
    "description": "Every HashUI component, the icon set, the theme provider and the token stylesheet, copied into your project in one command.",
    "type": "registry:ui",
    "target": "styles/hashui.css",
    "dependencies": [],
    "registryDependencies": []
  }
];
