/* GENERATED by scripts/build-registry.mjs — do not edit by hand. */

export type RegistryItem = {
  name: string;
  title: string;
  description: string;
  type: string;
  target: string;
  dependencies: string[];
  registryDependencies: string[];
};

export const REGISTRY_ITEMS: RegistryItem[] = [
  {
    "name": "tokens",
    "title": "Design tokens",
    "description": "Every design token in one file: surfaces, ink, brand, the button-face palette, both themes and the utility classes. Import it after Tailwind.",
    "type": "registry:theme",
    "target": "styles/uicean.css",
    "dependencies": [],
    "registryDependencies": []
  },
  {
    "name": "cx",
    "title": "cx",
    "description": "The three-line class-name joiner every component uses. No clsx, no tailwind-merge.",
    "type": "registry:lib",
    "target": "lib/uicean/cx.ts",
    "dependencies": [],
    "registryDependencies": [
      "tokens"
    ]
  },
  {
    "name": "icons",
    "title": "Icons",
    "description": "82 hand-drawn SVG icons on a 24px grid with a shared 1.8 stroke. Tree-shakeable, no icon package.",
    "type": "registry:ui",
    "target": "components/uicean/icons.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens"
    ]
  },
  {
    "name": "theme",
    "title": "ThemeProvider",
    "description": "light / dark / system with a persisted choice, plus the live sans-stack switcher behind useTheme().",
    "type": "registry:ui",
    "target": "components/uicean/theme.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens"
    ]
  },
  {
    "name": "button",
    "title": "Button",
    "description": "One anatomy — vertical gradient, 1px ring, hairline highlight — across eight faces. Plus ButtonGroup, IconButton and SplitButton.",
    "type": "registry:ui",
    "target": "components/uicean/button.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "badge",
    "title": "Badge & pill",
    "description": "StatusPill, DotPill, OutlineBadge, GlowPill, GlowDot, AnnouncementPill, CountBadge and Kbd — the whole status vocabulary.",
    "type": "registry:ui",
    "target": "components/uicean/badge.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "avatar",
    "title": "Avatar",
    "description": "Gradient-initial avatars with presence rings, overlapping AvatarGroup and the EntityChip company mark.",
    "type": "registry:ui",
    "target": "components/uicean/avatar.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "card",
    "title": "Card",
    "description": "Card, InsetPanel, StatTile, OverviewTile and MetaRow — the card-in-card layering the system uses instead of shadows.",
    "type": "registry:ui",
    "target": "components/uicean/card.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "controls",
    "title": "Controls",
    "description": "Switch, Checkbox, SegmentedControl and SearchField.",
    "type": "registry:ui",
    "target": "components/uicean/controls.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons"
    ]
  },
  {
    "name": "inputs",
    "title": "Inputs & selection",
    "description": "Slider, RadioGroup, RadioCards, SelectField, Accordion, Stepper, Pagination and Breadcrumbs.",
    "type": "registry:ui",
    "target": "components/uicean/inputs.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons"
    ]
  },
  {
    "name": "form",
    "title": "Form parts",
    "description": "Label, Textarea, Field, Separator, Toggle, ToggleGroup and Spinner. Field generates the ids and wires aria-describedby and aria-invalid, so a hint and an error are announced rather than merely shown.",
    "type": "registry:ui",
    "target": "components/uicean/form.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "table",
    "title": "Table & DataTable",
    "description": "Table, THead, TBody, Tr, Th and Td for a bespoke table; DataTable on top for columns-in-rows-out with sorting that reports itself on the header cell.",
    "type": "registry:ui",
    "target": "components/uicean/table.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons"
    ]
  },
  {
    "name": "overlay-primitives",
    "title": "Overlay primitives",
    "description": "useDismiss, useFocusTrap, useScrollLock and useAnchoredPosition — the four jobs every overlay has, written once. Anchoring is a rect, a flip and a clamp; no floating-ui.",
    "type": "registry:lib",
    "target": "lib/uicean/overlay-primitives.ts",
    "dependencies": [],
    "registryDependencies": [
      "tokens"
    ]
  },
  {
    "name": "popover",
    "title": "Popover & HoverCard",
    "description": "A panel anchored to a trigger. Popover opens on click and takes focus; HoverCard opens on hover and never does, because stealing focus from a passing pointer is hostile.",
    "type": "registry:ui",
    "target": "components/uicean/popover.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "overlay-primitives"
    ]
  },
  {
    "name": "sheet",
    "title": "Sheet & AlertDialog",
    "description": "A side panel and a confirmation. The sheet dismisses on Escape and on a click outside; the alert dialog does neither, because a stray click is not an answer.",
    "type": "registry:ui",
    "target": "components/uicean/sheet.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons",
      "button",
      "overlay-primitives"
    ]
  },
  {
    "name": "layout",
    "title": "Collapsible, ScrollArea, AspectRatio, InputOTP",
    "description": "The structural pieces. The OTP field is one real input behind six boxes, so a paste, a password manager and the browser's own SMS autofill all land.",
    "type": "registry:ui",
    "target": "components/uicean/layout.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons"
    ]
  },
  {
    "name": "combobox",
    "title": "Combobox & Command",
    "description": "A field that filters a list, at two scales. Focus stays in the field and the highlighted row is announced through aria-activedescendant.",
    "type": "registry:ui",
    "target": "components/uicean/combobox.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons",
      "overlay-primitives"
    ]
  },
  {
    "name": "calendar",
    "title": "Calendar & DatePicker",
    "description": "A month grid with no date library — Intl for the names, local midnight throughout, and a roving tab stop so it is one stop rather than forty-two.",
    "type": "registry:ui",
    "target": "components/uicean/calendar.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons",
      "popover"
    ]
  },
  {
    "name": "tabs",
    "title": "Tabs",
    "description": "PillTabs, NotchTabs, DotTabs, UnderlineTabs and PillNav — five tab treatments on one item model.",
    "type": "registry:ui",
    "target": "components/uicean/tabs.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "progress",
    "title": "Progress & meters",
    "description": "ProgressBar, TickBars, SignalBars, DottedMeter, GoalBar, RainbowMeter, RingProgress, RangeBar, CountdownLCD and LcdTimer.",
    "type": "registry:ui",
    "target": "components/uicean/progress.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "timeline",
    "title": "Timeline",
    "description": "DeliveryTimeline for ordered steps and StageFlow for service pipelines with protocol connectors.",
    "type": "registry:ui",
    "target": "components/uicean/timeline.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "badge",
      "icons"
    ]
  },
  {
    "name": "commit-graph",
    "title": "CommitGraph",
    "description": "A branching git graph with a hover card and diff counts — built for event-sourced history.",
    "type": "registry:ui",
    "target": "components/uicean/commit-graph.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "avatar",
      "icons"
    ]
  },
  {
    "name": "feedback",
    "title": "Feedback",
    "description": "Alert, ToastProvider + useToast, Tooltip, Skeleton and EmptyState.",
    "type": "registry:ui",
    "target": "components/uicean/feedback.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons"
    ]
  },
  {
    "name": "overlay",
    "title": "Overlay",
    "description": "Modal with focus and Esc handling, ModalClose, and the Dropdown menu.",
    "type": "registry:ui",
    "target": "components/uicean/overlay.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx",
      "icons"
    ]
  },
  {
    "name": "motion",
    "title": "Motion",
    "description": "NumberTicker, Typewriter, Marquee, ShimmerButton, BorderBeam, Spotlight, TiltCard, Reveal, Meteors and GradientText — all dependency-free.",
    "type": "registry:ui",
    "target": "components/uicean/motion.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "three-orb",
    "title": "ThreeOrb",
    "description": "A wireframe three.js scene that imports the library only once it scrolls into view.",
    "type": "registry:ui",
    "target": "components/uicean/three-orb.tsx",
    "dependencies": [
      "three"
    ],
    "registryDependencies": [
      "tokens",
      "cx"
    ]
  },
  {
    "name": "uicean",
    "title": "UICean — the whole library",
    "description": "Every UICean component, the icon set, the theme provider and the token stylesheet, copied into your project in one command.",
    "type": "registry:ui",
    "target": "styles/uicean.css",
    "dependencies": [],
    "registryDependencies": []
  },
  {
    "name": "blocks-tokens",
    "title": "Effects tokens",
    "description": "The .fx-* layer: the one place in UICean where glow is allowed, plus the grid, aurora, metal and marquee utilities the blocks use.",
    "type": "registry:theme",
    "target": "styles/uicean-blocks.css",
    "dependencies": [],
    "registryDependencies": [
      "tokens"
    ]
  },
  {
    "name": "blocks-hooks",
    "title": "Block hooks",
    "description": "useInView, useScrollProgress, useMagnetic, usePointer and useReducedMotion — the jobs framer-motion would otherwise be installed for.",
    "type": "registry:lib",
    "target": "lib/uicean/blocks-hooks.ts",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens"
    ]
  },
  {
    "name": "blocks-gl",
    "title": "Shader runner",
    "description": "runShader — compile, link, one full-screen triangle, capped DPR, pause off screen, freeze under reduced motion, and delete it all on unmount. The eighty lines every fragment-shader effect otherwise repeats.",
    "type": "registry:lib",
    "target": "lib/uicean/blocks-gl.ts",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens"
    ]
  },
  {
    "name": "blocks-parts",
    "title": "Block parts",
    "description": "ActionButton, Eyebrow, SplitHeadline, WindowFrame and WindowField — the small pieces every block is assembled from.",
    "type": "registry:ui",
    "target": "components/uicean/blocks-parts.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "button",
      "blocks-hooks"
    ]
  },
  {
    "name": "block-visuals",
    "title": "Block visuals",
    "description": "StatDial, FingerprintMark, Sparkline, AvatarStack, SetGlyph, IconTile and CropMarks — drawn illustrations, so a feature card never ships a stale PNG.",
    "type": "registry:ui",
    "target": "components/uicean/block-visuals.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "avatar"
    ]
  },
  {
    "name": "logo-cloud",
    "title": "LogoCloud",
    "description": "The social-proof grid in two treatments — plain rules, or plus marks on the interior crossings with a checkerboard tint.",
    "type": "registry:ui",
    "target": "components/uicean/logo-cloud.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "icons"
    ]
  },
  {
    "name": "integrations-marquee",
    "title": "IntegrationsMarquee",
    "description": "Three rows of integration chips drifting behind a radial mask, with your own mark held still in the middle.",
    "type": "registry:ui",
    "target": "components/uicean/integrations-marquee.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "motion",
      "icons",
      "blocks-parts"
    ]
  },
  {
    "name": "features-bento",
    "title": "FeaturesBento",
    "description": "An uneven twelve-column feature grid: a wide claim across the top, then cards that change width as the row goes on.",
    "type": "registry:ui",
    "target": "components/uicean/features-bento.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "card",
      "badge",
      "blocks-parts",
      "block-visuals"
    ]
  },
  {
    "name": "features-terminal",
    "title": "FeaturesTerminal",
    "description": "The developer-platform grid — every card opens with a terminal or an API exchange, given as data rather than as a screenshot.",
    "type": "registry:ui",
    "target": "components/uicean/features-terminal.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "card",
      "icons",
      "blocks-parts"
    ]
  },
  {
    "name": "features-crop",
    "title": "FeaturesCrop",
    "description": "Feature plates under printer's crop marks, closed by a full-width card with a row of captioned glyphs.",
    "type": "registry:ui",
    "target": "components/uicean/features-crop.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "icons",
      "block-visuals",
      "blocks-parts"
    ]
  },
  {
    "name": "hero-terminal",
    "title": "HeroTerminal",
    "description": "The developer-tool opening: announcement chip, two-tone headline, two calls to action, and the install running underneath.",
    "type": "registry:ui",
    "target": "components/uicean/hero-terminal.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "icons",
      "blocks-parts",
      "features-terminal"
    ]
  },
  {
    "name": "hero-split",
    "title": "HeroSplit",
    "description": "A real navigation bar, a left-aligned headline and a client strip — the marketing-site opening rather than a launch page.",
    "type": "registry:ui",
    "target": "components/uicean/hero-split.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "button",
      "icons",
      "blocks-parts",
      "logo-cloud"
    ]
  },
  {
    "name": "hero-nexus",
    "title": "HeroNexus",
    "description": "The SaaS opening: grouped nav menus, an announcement pill, a headline whose last word cycles, and an inline capture form.",
    "type": "registry:ui",
    "target": "components/uicean/hero-nexus.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "button",
      "motion",
      "icons",
      "blocks-parts",
      "blocks-hooks",
      "hero-split"
    ]
  },
  {
    "name": "hero-cinematic",
    "title": "HeroCinematic",
    "description": "A full-bleed still or loop, a floating pill of navigation, and the brand set enormous and cropped along the bottom edge.",
    "type": "registry:ui",
    "target": "components/uicean/hero-cinematic.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "blocks-hooks",
      "hero-split"
    ]
  },
  {
    "name": "spline-scene",
    "title": "SplineScene",
    "description": "A Spline 3D scene behind a dynamic import, so the runtime is fetched only once the block nears the viewport.",
    "type": "registry:ui",
    "target": "components/uicean/spline-scene.tsx",
    "dependencies": [
      "@splinetool/react-spline"
    ],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "motion",
      "blocks-hooks"
    ]
  },
  {
    "name": "auth-card",
    "title": "AuthCard",
    "description": "A sign-in / sign-up card that is a real form: submits on Enter, carries the autocomplete tokens a password manager matches on, and puts its error in a live region.",
    "type": "registry:ui",
    "target": "components/uicean/auth-card.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "button",
      "form",
      "controls",
      "icons"
    ]
  },
  {
    "name": "auth-split",
    "title": "AuthSplit",
    "description": "AuthCard with the other half of the screen given over to a quote and customer marks. The panel is dropped below lg rather than stacked above the form.",
    "type": "registry:ui",
    "target": "components/uicean/auth-split.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "auth-card"
    ]
  },
  {
    "name": "cinematic-footer",
    "title": "CinematicFooter",
    "description": "A tilted marquee band, an enormous sign-off, magnetic pills and a watermark — revealed by two CSS declarations rather than a scroll library.",
    "type": "registry:ui",
    "target": "components/uicean/cinematic-footer.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "icons",
      "blocks-hooks"
    ]
  },
  {
    "name": "grid-footer",
    "title": "GridFooter",
    "description": "A footer built as an exposed ruled grid rather than as stacked columns.",
    "type": "registry:ui",
    "target": "components/uicean/grid-footer.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "icons",
      "blocks-parts"
    ]
  },
  {
    "name": "dashboard-shell",
    "title": "DashboardShell",
    "description": "A workspace switcher, a nested navigation tree and a pinned footer group, wrapped in a collapsible rail with a top bar and a search overlay.",
    "type": "registry:ui",
    "target": "components/uicean/dashboard-shell.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "avatar",
      "badge",
      "icons"
    ]
  },
  {
    "name": "rail-sidebar",
    "title": "RailSidebar",
    "description": "The two-part admin navigation: a narrow rail of destinations, and a searchable panel holding the tree for the selected one.",
    "type": "registry:ui",
    "target": "components/uicean/rail-sidebar.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "controls",
      "icons"
    ]
  },
  {
    "name": "map",
    "title": "Map",
    "description": "A composable MapLibre surface whose markers are React children — Map, MapMarker, MarkerContent, MarkerDot, MarkerTooltip and MarkerLabel.",
    "type": "registry:ui",
    "target": "components/uicean/map.tsx",
    "dependencies": [
      "maplibre-gl"
    ],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx"
    ]
  },
  {
    "name": "globe-flights",
    "title": "GlobeFlights",
    "description": "A turning globe with great-circle routes and a glyph riding each arc, hidden as it passes behind the planet.",
    "type": "registry:ui",
    "target": "components/uicean/globe-flights.tsx",
    "dependencies": [
      "cobe"
    ],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "motion"
    ]
  },
  {
    "name": "liquid-metal-button",
    "title": "LiquidMetalButton",
    "description": "A brushed-metal pill with a turning sheen, a glowing rim and a ripple from wherever you clicked. No shader program.",
    "type": "registry:ui",
    "target": "components/uicean/liquid-metal-button.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "icons",
      "blocks-gl"
    ]
  },
  {
    "name": "gemini-ribbon",
    "title": "GeminiRibbon",
    "description": "Five ribbons that draw themselves as the page passes, each trailing a blurred copy of itself for the light.",
    "type": "registry:ui",
    "target": "components/uicean/gemini-ribbon.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx",
      "blocks-hooks"
    ]
  },
  {
    "name": "neural-vortex",
    "title": "NeuralVortex",
    "description": "A full-bleed WebGL backdrop of filaments that lean towards the pointer. One fragment shader, no dependencies.",
    "type": "registry:ui",
    "target": "components/uicean/neural-vortex.tsx",
    "dependencies": [],
    "registryDependencies": [
      "tokens",
      "blocks-tokens",
      "cx"
    ]
  }
];
